"""LLaVA-Instruct-150K manifest builder -- the D2 understanding extension.

Every record's image is a COCO ``train2017`` file (the dataset's own ``id``
field is the zero-padded COCO image id), so this module reuses
:func:`comppareto.data.split.assign_split` on the *same* normalized group key
(``str(int(image_id))``) that :mod:`comppareto.data.coco` uses -- an image
shared between D1 and D2 is therefore always assigned to the same split,
which is what makes the audited group-disjointness guarantee hold across
sources, not just within one source.

Only a bounded preview of each multi-turn conversation is stored in the
manifest (the first human/assistant turn plus a turn count) to keep the
frozen manifest file size auditable; the full conversation is recovered at
load time from the frozen raw ``llava_instruct_150k.json`` file referenced
by hash in ``configs/data/posttraining-v1/sources.yaml``.
"""

from __future__ import annotations

from collections import defaultdict
import json
from pathlib import Path
from typing import Any, Iterator

from .ids import stable_id
from .split import assign_split

LICENSE_TAG = "cc-by-4.0"
SOURCE_NAME = "llava_instruct_150k"
PREVIEW_CHAR_LIMIT = 240

#: Explicit, conservative project-level decision (2026-09-16) on LLaVA's
#: GPT-4-derived conversation text -- superseding the prior round's vague
#: "non-blocking caveat" framing. LLaVA-Instruct-150K's own release is
#: CC BY 4.0, but the conversation text itself was generated by prompting
#: GPT-4 with COCO metadata, so it is additionally covered by OpenAI's
#: Usage Policies, which restrict using Output "to develop any artificial
#: intelligence models that compete with OpenAI" without further
#: qualification of what counts as "compete." Rather than adjudicate that
#: ambiguity favorably, this project takes the conservative reading:
#: every D2 record derived from this source is marked
#: ``restricted_as_training_target=True`` and must not have its GPT-4-
#: authored assistant turn used as a raw gradient/label target in any
#: CompPareto post-training run (T270/T300/T400). The human
#: instruction/question text and the referenced COCO image are NOT GPT-4
#: output and remain unrestricted. A downstream task may only lift this
#: restriction for a specific run with an explicit, recorded local-review
#: sign-off overriding this default -- silence does not lift it. See
#: ``reports/T260/source-license-audit.md`` Sec. "D2" for the full
#: reasoning and citation of the OpenAI Usage Policies text consulted.
TRAINING_CONSTRAINTS: dict[str, Any] = {
    "restricted_as_training_target": True,
    "note": (
        "Conservative project decision (2026-09-16): this record's GPT-4-"
        "generated assistant turn text must not be used as a raw gradient "
        "training target/label in CompPareto post-training runs, per a "
        "conservative reading of OpenAI's Usage Policies restriction on "
        "using Output to develop a competing AI model. The human "
        "instruction/question and the referenced COCO train2017 image are "
        "not GPT-4 output and remain unrestricted. See "
        "reports/T260/source-license-audit.md."
    ),
}


def _first_turn_preview(conversations: list[dict[str, str]]) -> dict[str, Any]:
    human = next((turn["value"] for turn in conversations if turn.get("from") == "human"), "")
    assistant = next((turn["value"] for turn in conversations if turn.get("from") == "gpt"), "")
    human = human.replace("<image>", "").strip()
    return {
        "first_human_turn": human[:PREVIEW_CHAR_LIMIT],
        "first_assistant_turn": assistant[:PREVIEW_CHAR_LIMIT],
        "num_turns": len(conversations),
    }


def iter_records(json_path: Path) -> Iterator[dict[str, Any]]:
    """Yield deterministic D2 records built from ``llava_instruct_150k.json``.

    Iteration order follows the frozen file's own array order, which is
    itself a fixed artifact (identified by
    ``configs/data/posttraining-v1/sources.yaml``'s recorded sha256) -- no
    additional shuffling or re-sorting is applied, so results are
    reproducible byte-for-byte given the same input file.

    LLaVA-Instruct-150K's own ``id`` field identifies the *source COCO
    image*, not the conversation record: the released file legitimately
    contains multiple distinct conversation entries (e.g. a short
    ``conversation``, a ``detailed_description``, and a ``complex_reasoning``
    sample) sharing the same ``id`` for one image. Deriving ``record_id``
    from ``id`` alone therefore collided for ~61.9k ids (measured against
    the real 157,712-entry file; see
    ``reports/T260/failure-ledger.md``). To disambiguate deterministically
    without depending on any model outcome, this function appends each
    entry's zero-based *occurrence index within its own id*, counted in the
    frozen file's own fixed array order -- a pure function of the frozen
    input file's content and order alone.
    """
    with json_path.open("r", encoding="utf-8") as handle:
        entries = json.load(handle)
    occurrence_index: dict[str, int] = defaultdict(int)
    for entry in entries:
        image_id = str(int(entry["id"]))
        split = assign_split(image_id)
        index = occurrence_index[entry["id"]]
        occurrence_index[entry["id"]] += 1
        native_key = f"{entry['id']}:{index}"
        yield {
            "record_id": stable_id("d2-llava-instruct", native_key),
            "source": SOURCE_NAME,
            "role": "D2_understanding",
            "split": split,
            "group_key": image_id,
            "task_directions": ["vqa"],
            "license_tag": LICENSE_TAG,
            "source_native_id": native_key,
            "image": {
                "source_dataset": "coco_train2017",
                "source_relative_path": f"train2017/{entry['image']}",
                "metadata_admitted": True,
                "media_materialized": False,
                "media_verified_available": None,
                "media_sha256": None,
                "media_bytes": None,
            },
            "text": _first_turn_preview(entry["conversations"]),
            "training_constraints": dict(TRAINING_CONSTRAINTS),
        }
